coverage:
  status:
    patch:
      default:
        target: 80% # TODO revert to 80% when finishing Kover integration
        threshold: 1%
    project:
      default:
        target: 80% # TODO revert to 80% when finishing Kover integration
        threshold: 1%

ignore:
  - '**/build/**'

  # App
  - '**/KatanaApp.kt'
  - '**/initializers/**'

  # Common
  - '**/common/**'

  # Common Android
  - '**/*Activity'
  - '**/*Fragment'
  - '**/di/**'

  # Ui
  - '**/ui/**/components/**'
  - '**/ui/**/design/**'
  - '**/ui/**/navigation/**'
  - '**/ui/**/view/**'
