coverage:
  status:
    patch:
      default:
        target: 80%
        threshold: 1%
    project:
      default:
        target: 80%
        threshold: 1%

# Keep in sync with KatanaKoverPlugin
ignore:
  - '**/build/**'

  # Classes
  ## Common
  - '**/KatanaApp*.kt'
  - '**/KatanaBuildConfig.kt'

  ## Android
  - '**/*Activity'
  - '**/*Fragment'

  # Packages
  ## Base
  - '**/base/**'

  ## DI
  - '**/di/**'

  # UI
  - '**/ui/**/navigation/**'
  - '**/ui/**/resources/**'
  - '**/ui/**/strings/**'
  - '**/ui/**/view/**'
