ignore:
  - '**/build/**'

  # App
  - '**/KatanaApp.kt'
  - '**/initializers/**'

  # Common Android
  - '**/*Activity'
  - '**/*Fragment'
  - '**/base/**'
  - '**/navigation/**'

  # Ui
  - 'ui/**/view/**'

  # Utils
  - 'utils'
