name: Common Steps

description: Common steps for Katana workflows

inputs:
  gradle-encryption-key:
    description: 'Encryption key for Gradle cache'
    required: true

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        distribution: zulu
        java-version: 21
    - name: Setup Ruby
      uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # v1.300.0
      with:
        bundler-cache: true
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
      with:
        add-job-summary-as-pr-comment: on-failure
        artifact-retention-days: 7
        build-scan-publish: true
        build-scan-terms-of-use-url: https://gradle.com/help/legal-terms-of-use
        build-scan-terms-of-use-agree: yes
        cache-encryption-key: ${{ inputs.gradle-encryption-key }}
        dependency-graph: generate-and-submit
