name: Common Steps

description: Common steps for Katana workflows

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
