name: Common Steps

description: Common steps for Katana workflows

inputs:
  gradle-encryption-key:
    description: 'Encryption key for Gradle cache'
    required: true

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
      with:
        distribution: zulu
        java-version: 21
    - name: Setup Ruby
      uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
      with:
        bundler-cache: true
    - name: Restore Kotlin/Native cache
      if: runner.os == 'macOS' && github.event_name == 'pull_request'
      uses: actions/cache/restore@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
      with:
        path: ~/.konan
        key: konan-${{ runner.os }}-${{ hashFiles('gradle/libs.versions.toml') }}
        restore-keys: |
          konan-${{ runner.os }}-
    - name: Cache Kotlin/Native
      if: runner.os == 'macOS' && github.event_name != 'pull_request'
      uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
      with:
        path: ~/.konan
        key: konan-${{ runner.os }}-${{ hashFiles('gradle/libs.versions.toml') }}
        restore-keys: |
          konan-${{ runner.os }}-
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
      with:
        add-job-summary-as-pr-comment: on-failure
        artifact-retention-days: 7
        build-scan-publish: true
        build-scan-terms-of-use-url: https://gradle.com/help/legal-terms-of-use
        build-scan-terms-of-use-agree: yes
        cache-encryption-key: ${{ inputs.gradle-encryption-key }}
        dependency-graph: generate-and-submit
