name: Common Steps

description: Common steps for Katana workflows

inputs:
  gradle-encryption-key:
    description: 'Encryption key for Gradle cache'
    required: true

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        distribution: zulu
        java-version: 21
    - name: Setup Ruby
      uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1.313.0
      with:
        bundler-cache: true
    - name: Restore Kotlin/Native cache
      if: runner.os == 'macOS' && github.event_name == 'pull_request'
      uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ~/.konan
        key: konan-${{ runner.os }}-${{ hashFiles('gradle/libs.versions.toml') }}
        restore-keys: |
          konan-${{ runner.os }}-
    - name: Cache Kotlin/Native
      if: runner.os == 'macOS' && github.event_name != 'pull_request'
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ~/.konan
        key: konan-${{ runner.os }}-${{ hashFiles('gradle/libs.versions.toml') }}
        restore-keys: |
          konan-${{ runner.os }}-
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
      with:
        add-job-summary-as-pr-comment: on-failure
        artifact-retention-days: 7
        build-scan-publish: true
        build-scan-terms-of-use-url: https://gradle.com/help/legal-terms-of-use
        build-scan-terms-of-use-agree: yes
        cache-encryption-key: ${{ inputs.gradle-encryption-key }}
        dependency-graph: generate-and-submit
