name: Common Steps

description: Common steps for Katana workflows

inputs:
  gradle-encryption-key:
    description: 'Encryption key for Gradle cache'
    required: true

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4.2.0
      with:
        distribution: zulu
        java-version: 17
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3.1.0
      with:
        add-job-summary-as-pr-comment: on-failure
        artifact-retention-days: 7
        build-scan-publish: true
        build-scan-terms-of-service-url: https://gradle.com/terms-of-service
        build-scan-terms-of-service-agree: yes
        cache-encryption-key: ${{ inputs.gradle-encryption-key }}
        dependency-graph: generate-and-submit
        gradle-home-cache-cleanup: true
