android:
  dev:
    - type: Boolean
      name: DEBUG
      value: true
  beta:
    - type: Boolean
      name: DEBUG
      value: false
  release:
    - type: Boolean
      name: DEBUG
      value: false
ios:
  dev:
    - type: Boolean
      name: DEBUG
      value: true
  beta:
    - type: Boolean
      name: DEBUG
      value: false
  release:
    - type: Boolean
      name: DEBUG
      value: false
