target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'

  pod 'commonCore', :path => '../common/core'

  pod 'dataPreferencesBase', :path => '../data/preferences/base'
  pod 'dataPreferencesSession', :path => '../data/preferences/session'

  pod 'dataRemoteBase', :path => '../data/remote/base'
  pod 'dataRemoteAccount', :path => '../data/remote/account'
  pod 'dataRemoteExplore', :path => '../data/remote/explore'
  pod 'dataRemoteLists', :path => '../data/remote/lists'
  pod 'dataRemoteSocial', :path => '../data/remote/social'
  pod 'dataRemoteUser', :path => '../data/remote/user'

  pod 'domainBase', :path => '../domain/base'
  pod 'domainAccount', :path => '../domain/account'
  pod 'domainExplore', :path => '../domain/explore'
  pod 'domainLists', :path => '../domain/lists'
  pod 'domainSession', :path => '../domain/session'
  pod 'domainSocial', :path => '../domain/social'
  pod 'domainUser', :path => '../domain/user'

  pod 'uiBase', :path => '../ui/base'
  pod 'uiAccount', :path => '../ui/account'
  pod 'uiExplore', :path => '../ui/explore'
  pod 'uiLists', :path => '../ui/lists'
  pod 'uiLogin', :path => '../ui/login'
  pod 'uiMain', :path => '../ui/main'
  pod 'uiSocial', :path => '../ui/social'

  post_install do |installer|
   installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
     target.build_configurations.each do |config|
       config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
     end
    end
   end
  end
end
