[versions]
accompanist = "0.24.12-rc"
apollo = "3.3.2"
coroutines = "1.6.3"
destinations = "1.5.9-beta"
hilt = "2.42"
hiltx = "1.0.0"
kotlin = "1.7.0"
lifecycle = "2.5.0"
okhttp = "4.10.0"
orbit = "4.3.2"

# Compose
compose = "1.2.0-rc03"
compose-compiler = "1.2.0-rc02"

# Coverage Engine
intellij = "1.0.673"

# Plugins
detekt = "1.20.0"

# Tests
androidx-test = "1.4.0"
kotest = "5.3.2"
mockk = "1.12.4"

[plugins]
apollo = { id = "com.apollographql.apollo3", version.ref = "apollo" }

[libraries]
# Accompanist
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }

# AndroidX
androidx-activity = { module = "androidx.activity:activity-compose", version = "1.5.0" }
androidx-startup = { module = "androidx.startup:startup-runtime", version = "1.1.1" }

# Apollo
apollo = { module = "com.apollographql.apollo3:apollo-runtime", version.ref = "apollo" }
apollo-cache = { module = "com.apollographql.apollo3:apollo-normalized-cache", version.ref = "apollo" }
apollo-cache-sql = { module = "com.apollographql.apollo3:apollo-normalized-cache-sqlite", version.ref = "apollo" }
apollo-mockserver = { module = "com.apollographql.apollo3:apollo-mockserver", version.ref = "apollo" }
apollo-testing = { module = "com.apollographql.apollo3:apollo-testing-support", version.ref = "apollo" }

# Arrow
arrow = { module = "io.arrow-kt:arrow-core", version = "1.1.2" }

# Compose
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-fonts = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-test-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }

# Coroutines
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

# DataStore
datastore = { module = "androidx.datastore:datastore", version = "1.0.0" }

# Destiantions
destinations = { module = "io.github.raamcosta.compose-destinations:animations-core", version.ref = "destinations" }
destinations-compiler = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "destinations" }

# Desugaring
desugaring = { module = "com.android.tools:desugar_jdk_libs", version = "1.1.6" }

# Detekt
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

# Gradle
gradle-android = { module = "com.android.tools.build:gradle", version = "7.2.1" }
gradle-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
gradle-hilt = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-kover = { module = "org.jetbrains.kotlinx:kover", version = "0.5.1" }
gradle-ksp = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version = "1.6.21-1.0.5" }
gradle-sentry = { module = "io.sentry:sentry-android-gradle-plugin", version = "3.1.2" }
gradle-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
gradle-sonarqube = { module = "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin", version = "3.4.0.2513" }
gradle-updates = { module = "com.github.ben-manes:gradle-versions-plugin", version = "0.42.0" }

# Hilt
hilt = { module = "com.google.dagger:hilt-core", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-test = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }

# HiltX
hiltx-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltx" }
hiltx-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltx" }

# Kotlin
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

# LeakCanary
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.9.1" }

# Lifecycle
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-test = { module = "androidx.lifecycle:lifecycle-runtime-testing", version.ref = "lifecycle" }

# Napier
napier = { module = "io.github.aakira:napier", version = "2.6.1" }

# OkHttp
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logger = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

# Orbit
orbit = { module = "org.orbit-mvi:orbit-viewmodel", version.ref = "orbit" }
orbit-compose = { module = "org.orbit-mvi:orbit-compose", version.ref = "orbit" }
orbit-test = { module = "org.orbit-mvi:orbit-test", version.ref = "orbit" }

# Sentry
sentry = { module = "io.sentry:sentry-android-core", version = "6.1.4" }

# Serialization
protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version = "1.3.3" }

# Tests
## AndroidX Test
androidx-test = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
androidx-test-junit = { module = "androidx.test.ext:junit-ktx", version = "1.1.3" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }

## Kotest
kotest = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-arrow = { module = "io.kotest.extensions:kotest-assertions-arrow", version = "1.2.5" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }

## MockK
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }

## Turbine
turbine = { module = "app.cash.turbine:turbine", version = "0.8.0" }

[bundles]
gradle = [
    "gradle-android",
    "gradle-detekt",
    "gradle-hilt",
    "gradle-kotlin",
    "gradle-kover",
    "gradle-ksp",
    "gradle-sentry",
    "gradle-serialization",
    "gradle-sonarqube",
    "gradle-updates",
]

common = [
    "arrow",
    "coroutines",
    "hilt",
    "kotlin",
]
common-android = [
    "arrow",
    "coroutines-android",
    "hilt-android",
    "kotlin",
    "napier",
]

app = [
    "androidx-activity",
    "androidx-startup",
    "compose-material",
    "compose-material-icons",
    "destinations",
    "hiltx-navigation",
    "sentry",
]

kapt = [
    "hilt-compiler",
]
kapt-ui = [
    "hilt-compiler",
    "hiltx-compiler",
]

ksp-ui = [
    "destinations-compiler",
]

data-preferences = [
    "datastore",
    "protobuf",
]
data-remote = [
    "apollo",
    "apollo-cache",
]

ui-compose = [
    "accompanist-pager",
    "accompanist-pager-indicators",
    "compose-animation",
    "compose-foundation",
    "compose-foundation-layout",
    "compose-material",
    "compose-material-icons",
    "compose-ui",
    "compose-ui-tooling",
    "destinations",
    "hiltx-navigation",
    "lifecycle-viewmodel",
    "orbit",
    "orbit-compose",
]

test = [
    "coroutines-test",
    "kotest",
    "kotest-assertions-arrow",
    "kotest-assertions-core",
    "kotest-property",
    "mockk",
    "orbit-test",
    "turbine",
]
test-android = [
    "coroutines-test",
    "androidx-test",
    "androidx-test-junit",
    "androidx-test-rules",
    "androidx-test-runner",
    "hilt-test",
    "kotest-assertions-arrow",
    "kotest-assertions-core",
    "mockk-android",
    "turbine",
]

test-data-remote = [
    "apollo-mockserver",
    "apollo-testing",
]
test-ui = [
    "compose-ui-test-junit",
    "lifecycle-test",
]
