[versions]
accompanist = "0.32.0"
apollo = "3.8.2"
compose = "1.5.1"
coroutines = "1.7.3"
datastore = "1.1.0-alpha05"
destinations = "1.9.53"
detekt = "1.23.1"
junit5 = "5.10.0"
koin = "3.5.0"
koin-compose = "3.4.5"
koin-test = "3.5.0"
kotest = "5.7.2"
kotlin = "1.9.10"
ktor = "2.3.4"
lifecycle = "2.6.2"
mockmp = "1.15.0"
orbit = "6.1.0"
sentry = "6.29.0"

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
parcelize = { id = "com.arkivanov.parcelize.darwin", version = "0.2.1" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
# Accompanist
accompanist-placeholder = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

# AndroidX
androidx-activity = { module = "androidx.activity:activity-compose", version = "1.7.2" }

# Apollo
apollo = { module = "com.apollographql.apollo3:apollo-runtime", version.ref = "apollo" }
apollo-cache = { module = "com.apollographql.apollo3:apollo-normalized-cache-sqlite", version.ref = "apollo" }
apollo-mockserver = { module = "com.apollographql.apollo3:apollo-mockserver", version.ref = "apollo" }
apollo-test = { module = "com.apollographql.apollo3:apollo-testing-support", version.ref = "apollo" }

# Arrow
arrow = { module = "io.arrow-kt:arrow-core", version = "1.2.1" }

# Compose
compose-compiler = { module = "org.jetbrains.compose.compiler:compiler", version = "1.5.2" }
compose-material3-windowsize = { module = "dev.chrisbanes.material3:material3-window-size-class-multiplatform", version = "0.3.1" }

# Coroutines
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

# Datastore
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
datastore-okio = { module = "androidx.datastore:datastore-core-okio", version.ref = "datastore" }

# Destiantions
destinations = { module = "io.github.raamcosta.compose-destinations:animations-core", version.ref = "destinations" }
destinations-compiler = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "destinations" }

# Detekt
detekt-compose = { module = "io.nlopez.compose.rules:detekt", version = "0.2.3" }
detekt-compose2 = { module = "ru.kode:detekt-rules-compose", version = "1.3.0" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

# Gradle
gradle-android = { module = "com.android.tools.build:gradle", version = "8.1.1" }
gradle-apollo = { module = "com.apollographql.apollo3:apollo-gradle-plugin", version.ref = "apollo" }
gradle-buildconfig = { module = "com.github.gmazzo.buildconfig:plugin", version = "4.1.2" }
gradle-complete-kotlin = { module = "com.louiscad.complete-kotlin:plugin", version = "1.1.0" }
gradle-compose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose" }
gradle-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
gradle-kotest = { module = "io.kotest:kotest-framework-multiplatform-plugin-gradle", version.ref = "kotest" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-kover = { module = "org.jetbrains.kotlinx:kover-gradle-plugin", version = "0.7.3" }
gradle-ksp = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version = "1.9.10-1.0.13" }
gradle-mockmp = { module = "org.kodein.mock:mockmp-gradle-plugin", version.ref = "mockmp" }
gradle-sentry = { module = "io.sentry:sentry-android-gradle-plugin", version = "3.12.0" }
gradle-sonarqube = { module = "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin", version = "4.3.1.3277" }
gradle-updates = { module = "com.github.ben-manes:gradle-versions-plugin", version = "0.48.0" }

# Kamel
kamel = { module = "media.kamel:kamel-image", version = "0.7.3" }

# Kermit
kermit = { module = "co.touchlab:kermit", version = "2.0.0-RC5" }

# Klock
klock = { module = "com.soywiz.korlibs.klock:klock", version = "4.0.10" }

# Koin
koin = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version = "1.1.0" }
koin-compose-android = { module = "io.insert-koin:koin-androidx-compose", version = "3.5.0" }
koin-junit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin-test" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin-test" }

# Kotlin
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version = "0.3.5" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version = "1.6.0" }

# Ktor
ktor-android = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-ios = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }

# Lifecycle
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }

# Lyricist
lyricist = { module = "cafe.adriel.lyricist:lyricist", version = "1.4.2" }

# Okio
okio-fakefilesystem = { module = "com.squareup.okio:okio-fakefilesystem", version = "3.5.0" }

# Orbit
orbit = { module = "org.orbit-mvi:orbit-viewmodel", version.ref = "orbit" }
orbit-test = { module = "org.orbit-mvi:orbit-test", version.ref = "orbit" }

# Parcelable
parcelable = { module = "com.arkivanov.essenty:parcelable", version = "1.1.0" }

# Sentry
sentry = { module = "io.sentry:sentry-android-core", version.ref = "sentry" }
sentry-apollo = { module = "io.sentry:sentry-apollo-3", version.ref = "sentry" }
sentry-compose = { module = "io.sentry:sentry-compose-android", version.ref = "sentry" }
sentry-multiplatform = { module = "io.sentry:sentry-kotlin-multiplatform", version = "0.2.1" }

# Tink
tink = { module = "com.google.crypto.tink:tink-android", version = "1.10.0" }

# YAML
yamlbeans = { module = "com.esotericsoftware.yamlbeans:yamlbeans", version = "1.15" }

# Tests
## JUnit
junit5 = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5" }
junit5-vintage = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit5" }

## Kotest
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }

## MockK
mockk = { module = "io.mockk:mockk", version = "1.13.7" }

## MocKMP
mockmp = { module = "org.kodein.mock:mockmp-runtime", version.ref = "mockmp" }

## Turbine
turbine = { module = "app.cash.turbine:turbine", version = "1.0.0" }

[bundles]
# Deps for Multiplatform Core (Common, JVM & iOS)
core-common = [
    "arrow",
    "coroutines",
    "klock",
    "koin",
    "kotlin",
    "kotlin-immutable",
]
core-jvm = []
core-ios = []

core-common-ksp = []
core-jvm-ksp = []
core-ios-ksp = []

core-common-test = [
    "coroutines-test",
    "koin-test",
    "kotest-assertions-core",
    "kotest-engine",
    "kotest-property",
    "turbine",
]
core-jvm-test = [
    "junit5",
    "kotest-junit5",
    "mockk",
]
core-ios-test = []

# Deps for Multiplatform Mobile (Common, Android & iOS)
mobile-common = [
    "arrow",
    "coroutines",
    "klock",
    "koin",
    "kotlin",
    "kotlin-immutable",
    "kermit",
]
mobile-android = [
    "koin-android",
    "ktor-android",
]
mobile-ios = [
    "ktor-ios",
]

mobile-common-ksp = []
mobile-android-ksp = []
mobile-ios-ksp = []

mobile-common-test = [
    "coroutines-test",
    "koin-test",
    "kotest-assertions-core",
    "kotest-engine",
    "kotest-property",
    "turbine",
]
mobile-android-test = [
    "junit5",
    "junit5-vintage",
    "kotest-junit5",
    "mockk",
]
mobile-ios-test = []

# Deps for Data Preferences
data-preferences-common = [
    "datastore",
    "datastore-okio",
    "kotlin-serialization",
]
data-preferences-android = [
    "tink",
]
data-preferences-ios = []

data-preferences-common-test = [
    "okio-fakefilesystem",
]
data-preferences-android-test = []
data-preferences-ios-test = []

# Deps for Data Remote
data-remote-common = [
    "apollo",
    "apollo-cache",
]
data-remote-android = []
data-remote-ios = []

data-remote-common-test = [
    "apollo-test",
]
data-remote-android-test = [
    "apollo-mockserver",
]
data-remote-ios-test = []

# Deps for UI
ui-common = [
    "kamel",
    "koin-compose",
    "lyricist",
]
ui-android = [
    "accompanist-placeholder",
    "destinations",
    "koin-compose-android",
    "lifecycle-runtime",
    "lifecycle-viewmodel",
    "orbit",
]
ui-ios = []

ui-common-ksp = []
ui-android-ksp = [
    "destinations-compiler",
]
ui-ios-ksp = []

ui-common-test = []
ui-android-test = [
    "koin-junit4",
    "orbit-test",
]
ui-ios-test = []

app = [
    "androidx-activity",
    "sentry",
]
