[versions]
compose = "1.1.0-rc01"
compose-compiler = "1.1.0-rc02"
kotlin = "1.6.10"

# Plugins
detekt = "1.19.0"

# Tests
kotest = "5.1.0"

[libraries]
# AndroidX
androidx-activity = { module = "androidx.activity:activity-compose", version = "1.4.0" }
androidx-core = { module = "androidx.core:core-ktx", version = "1.7.0" }

# Compose
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }

# Design
design-material = { module = "com.google.android.material:material", version = "1.5.0" }

# Detekt
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

# Gradle
gradle-android = { module = "com.android.tools.build:gradle", version = "7.0.4" }
gradle-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-updates = { module = "com.github.ben-manes:gradle-versions-plugin", version = "0.41.0" }

# Kotlin
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

# Tests
## AndroidX Test
androidx-test-junit = { module = "androidx.test.ext:junit-ktx", version = "1.1.3" }

## Kotest
kotest = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }

[bundles]
test = [
    "kotest",
    "kotest-assertions-core",
]
