[versions]
accompanist = "0.28.0"
apollo = "3.7.3"
coroutines = "1.6.4"
destinations = "1.7.30-beta"
hilt = "2.44.2"
hiltx = "1.0.0"
junit5 = "5.9.2"
kotlin = "1.8.0"
okhttp = "4.10.0"
orbit = "4.5.0"
sentry = "6.11.0"

# Compose
compose = "2022.12.00"
compose-compiler = "1.4.0-dev-k1.8.0-33c0ad36f83"

# Coverage Engine
coverage-engine = "1.0.691"

# Plugins
detekt = "1.22.0"

# Tests
kotest = "5.5.4"

[plugins]
apollo = { id = "com.apollographql.apollo3", version.ref = "apollo" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
# Accompanist
accompanist-placeholder = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

# AndroidX
androidx-activity = { module = "androidx.activity:activity-compose", version = "1.6.1" }
androidx-startup = { module = "androidx.startup:startup-runtime", version = "1.1.1" }

# Apollo
apollo = { module = "com.apollographql.apollo3:apollo-runtime", version.ref = "apollo" }
apollo-cache = { module = "com.apollographql.apollo3:apollo-normalized-cache", version.ref = "apollo" }
apollo-cache-sql = { module = "com.apollographql.apollo3:apollo-normalized-cache-sqlite", version.ref = "apollo" }
apollo-mockserver = { module = "com.apollographql.apollo3:apollo-mockserver", version.ref = "apollo" }
apollo-test = { module = "com.apollographql.apollo3:apollo-testing-support", version.ref = "apollo" }

# Arrow
arrow = { module = "io.arrow-kt:arrow-core", version = "1.1.3" }

# Coil
coil = { module = "io.coil-kt:coil-compose", version = "2.2.2" }

# Compose
compose-animation = { module = "androidx.compose.animation:animation" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
compose-material = { module = "androidx.compose.material:material" }
compose-material3-windowsize = { module = "androidx.compose.material3:material3-window-size-class" }
compose-material-icons = { module = "androidx.compose.material:material-icons-extended" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

# Coroutines
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

# DataStore
datastore = { module = "androidx.datastore:datastore", version = "1.0.0" }

# Design
design-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version = "1.0.1" }

# Destiantions
destinations = { module = "io.github.raamcosta.compose-destinations:animations-core", version.ref = "destinations" }
destinations-compiler = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "destinations" }

# Desugaring
desugaring = { module = "com.android.tools:desugar_jdk_libs", version = "1.2.2" }

# Detekt
detekt-compose = { module = "com.twitter.compose.rules:detekt", version = "0.0.26" }
detekt-compose2 = { module = "ru.kode:detekt-rules-compose", version = "1.2.2" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

# Gradle
gradle-android = { module = "com.android.tools.build:gradle", version = "7.3.1" }
gradle-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
gradle-hilt = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-kover = { module = "org.jetbrains.kotlinx.kover:org.jetbrains.kotlinx.kover.gradle.plugin", version = "0.6.1" }
gradle-ksp = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version = "1.8.0-1.0.8" }
gradle-sentry = { module = "io.sentry:sentry-android-gradle-plugin", version = "3.4.0" }
gradle-sonarqube = { module = "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin", version = "3.4.0.2513" }
gradle-updates = { module = "com.github.ben-manes:gradle-versions-plugin", version = "0.44.0" }

# Hilt
hilt = { module = "com.google.dagger:hilt-core", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-test = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }

# HiltX
hiltx-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltx" }
hiltx-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltx" }

# Kotlin
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version = "0.3.5" }

# Lifecycle
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version = "2.5.1" }

# Napier
napier = { module = "io.github.aakira:napier", version = "2.6.1" }

# OkHttp
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logger = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

# Orbit
orbit = { module = "org.orbit-mvi:orbit-viewmodel", version.ref = "orbit" }
orbit-compose = { module = "org.orbit-mvi:orbit-compose", version.ref = "orbit" }
orbit-test = { module = "org.orbit-mvi:orbit-test", version.ref = "orbit" }

# Sentry
sentry = { module = "io.sentry:sentry-android-core", version.ref = "sentry" }
sentry-apollo = { module = "io.sentry:sentry-apollo-3", version.ref = "sentry" }
sentry-compose = { module = "io.sentry:sentry-compose-android", version.ref = "sentry" }

# Serialization
protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version = "1.4.1" }

# Tink
tink = { module = "com.google.crypto.tink:tink-android", version = "1.7.0" }

# Tests
## JUnit
junit5 = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5" }
junit5-vintage = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit5" }

## Kotest
kotest-assertions-arrow = { module = "io.kotest.extensions:kotest-assertions-arrow", version = "1.3.0" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }

## MockK
mockk = { module = "io.mockk:mockk", version = "1.13.3" }

## Robolectric
robolectric = { module = "org.robolectric:robolectric", version = "4.9.2" }

## Turbine
turbine = { module = "app.cash.turbine:turbine", version = "0.12.1" }

[bundles]
common = [
    "arrow",
    "coroutines",
    "hilt",
    "kotlin",
    "kotlin-immutable",
]
common-android = [
    "arrow",
    "coroutines-android",
    "hilt-android",
    "kotlin",
    "kotlin-immutable",
    "napier",
]

app = [
    "androidx-activity",
    "androidx-startup",
    "compose-material",
    "compose-material3-windowsize",
    "compose-material-icons",
    "destinations",
    "hiltx-navigation",
    "orbit",
    "orbit-compose",
    "sentry",
    "sentry-compose",
]

kapt = [
    "hilt-compiler",
]
kapt-ui = [
    "hilt-android-compiler",
    "hiltx-compiler",
]

ksp-ui = [
    "destinations-compiler",
]

data-preferences = [
    "datastore",
    "protobuf",
    "tink",
]
data-remote = [
    "apollo",
    "apollo-cache",
]

ui-compose = [
    "accompanist-placeholder",
    "coil",
    "compose-animation",
    "compose-foundation",
    "compose-foundation-layout",
    "compose-material",
    "compose-material-icons",
    "compose-ui",
    "compose-ui-tooling",
    "design-constraintlayout",
    "destinations",
    "hiltx-navigation",
    "lifecycle-viewmodel",
    "orbit",
    "orbit-compose",
]

test = [
    "coroutines-test",
    "junit5",
    "kotest-assertions-arrow",
    "kotest-assertions-core",
    "kotest-property",
    "mockk",
    "turbine",
]
test-android = [
    "hilt-test",
    "junit5-vintage",
    "robolectric",
]

test-data-remote = [
    "apollo-mockserver",
    "apollo-test",
]
test-ui = [
    "compose-ui-test",
    "orbit-test",
]
