[versions]
android = "9.3.1"
androidx-activity = "1.13.0"
androidx-benchmark = "1.5.0-beta01"
androidx-splashscreen = "1.2.0"
androidx-test-ext-junit = "1.3.0"
apollo = "5.0.1"
apollo-cache = "1.0.6"
apollo-mockserver = "0.3.1"
arrow = "2.2.3"
baselineprofile = "1.5.0-beta01"
coil = "3.5.0"
compose = "1.12.0-beta03"
compose-placeholder = "1.0.12"
compose-stability-analyzer = "0.12.0"
desugaring = "2.1.5"
detekt = "2.0.0-alpha.6"
detekt-compose = "0.6.4"
detekt-compose2 = "1.4.0"
kermit = "2.1.0"
kaml = "0.104.0"
kotest = "6.2.3"
kotlin = "2.4.10"
kotlinpoet = "2.3.0"
kotlinx-atomicfu = "0.33.0"
kotlinx-coroutines = "1.11.0"
kotlinx-datetime = "0.8.0-0.6.x-compat"
kotlinx-immutable = "0.5.1"
kotlinx-serialization = "1.11.0"
kover = "0.9.9"
ksafe = "3.0.0"
ksp = "2.3.11"
ktor = "3.5.2"
lifecycle = "2.11.0"
material3 = "1.12.0-alpha03"
material3-adaptive = "1.3.0-beta02"
materialkolor = "5.0.0"
metro = "1.4.1"
mockk = "1.14.11"
mokkery = "3.4.2"
navigation = "2.10.0-alpha02"
navigation3 = "1.2.0-alpha02"
navigation-material = "1.12.0-beta03"
okio = "3.18.1"
spotless = "8.9.0"
turbine = "1.2.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "android" }
androidx-baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
apollo = { id = "com.apollographql.apollo", version.ref = "apollo" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-stability-analyzer = { id = "com.github.skydoves.compose.stability.analyzer", version.ref = "compose-stability-analyzer" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
kotest = { id = "io.kotest", version.ref = "kotest" }
kotlin = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
metro = { id = "dev.zacsweers.metro", version.ref = "metro" }
mokkery = { id = "dev.mokkery", version.ref = "mokkery" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
# AndroidX
androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-benchmark-macro-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "androidx-benchmark" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-splashscreen" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }

# Apollo
apollo = { module = "com.apollographql.apollo:apollo-runtime", version.ref = "apollo" }
apollo-cache = { module = "com.apollographql.cache:normalized-cache", version.ref = "apollo-cache" }
apollo-cache-plugin = { module = "com.apollographql.cache:normalized-cache-apollo-compiler-plugin", version.ref = "apollo-cache" }
apollo-cache-sqlite = { module = "com.apollographql.cache:normalized-cache-sqlite", version.ref = "apollo-cache" }
apollo-mockserver = { module = "com.apollographql.mockserver:apollo-mockserver", version.ref = "apollo-mockserver" }
apollo-test = { module = "com.apollographql.apollo:apollo-testing-support", version.ref = "apollo" }

# Arrow
arrow = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }

# Coil
coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }

# Compose
compose-animation = { module = "org.jetbrains.compose.animation:animation", version.ref = "compose" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
compose-material3-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "material3-adaptive" }
compose-placeholder = { module = "com.eygraber:compose-placeholder-material3", version.ref = "compose-placeholder" }
compose-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-runtime-saveable = { module = "org.jetbrains.compose.runtime:runtime-saveable", version.ref = "compose" }
compose-stability-analyzer-runtime = { module = "com.github.skydoves:compose-stability-runtime", version.ref = "compose-stability-analyzer" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
compose-windowsize = { module = "org.jetbrains.compose.material3:material3-window-size-class", version.ref = "material3" }

# Detekt
detekt-compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detekt-compose" }
detekt-compose2 = { module = "ru.kode:detekt-rules-compose", version.ref = "detekt-compose2" }
detekt-rules = { module = "dev.detekt:detekt-rules", version.ref = "detekt" }

# Desugaring
desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugaring" }

# Gradle
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "android" }
gradle-apollo = { module = "com.apollographql.apollo:apollo-gradle-plugin", version.ref = "apollo" }
gradle-baselineprofile = { module = "androidx.baselineprofile:androidx.baselineprofile.gradle.plugin", version.ref = "baselineprofile" }
gradle-compose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose" }
gradle-compose-compiler = { module = "org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin", version.ref = "kotlin" }
gradle-compose-stability-analyzer = { module = "com.github.skydoves.compose.stability.analyzer:com.github.skydoves.compose.stability.analyzer.gradle.plugin", version.ref = "compose-stability-analyzer" }
gradle-detekt = { module = "dev.detekt:detekt-gradle-plugin", version.ref = "detekt" }
gradle-kotest = { module = "io.kotest:io.kotest.gradle.plugin", version.ref = "kotest" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-kover = { module = "org.jetbrains.kotlinx:kover-gradle-plugin", version.ref = "kover" }
gradle-ksp = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp" }
gradle-metro = { module = "dev.zacsweers.metro:gradle-plugin", version.ref = "metro" }
gradle-mokkery = { module = "dev.mokkery:mokkery-gradle", version.ref = "mokkery" }
gradle-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

# Kaml
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }

# Kermit
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

# Kotlin
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinx-atomicfu" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-immutable" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# KotlinPoet
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }

# KSafe
ksafe = { module = "eu.anifantakis:ksafe", version.ref = "ksafe" }

# Ktor
ktor-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-ios = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }

# Lifecycle
lifecycle-runtime = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }

# MaterialKolor
materialkolor = { module = "com.materialkolor:material-kolor", version.ref = "materialkolor" }

# Metro
metrox-android = { module = "dev.zacsweers.metro:metrox-android", version.ref = "metro" }
metrox-viewmodel = { module = "dev.zacsweers.metro:metrox-viewmodel-compose", version.ref = "metro" }

# Navigation
navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation" }
navigation-material = { module = "org.jetbrains.compose.material:material-navigation", version.ref = "navigation-material" }
navigation3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "navigation3" }

# Okio
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }

# Tests
## Kotest
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-property-datetime = { module = "io.kotest:kotest-property-datetime", version.ref = "kotest" }

## MockK
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

## Turbine
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[bundles]
# Deps for Core
core-common = [
    "arrow",
    "kotlin",
    "kotlinx-coroutines",
    "kotlinx-datetime",
    "kotlinx-immutable",
    "kermit",
    "okio",
]
core-android = []
core-ios = []

core-common-ksp = []
core-android-ksp = []
core-ios-ksp = []

core-common-test = [
    "kotest-assertions-core",
    "kotest-engine",
    "kotest-property",
    "kotlinx-coroutines-test",
    "kotest-property-datetime",
    "turbine",
]
core-android-test = [
    "kotest-junit5",
    "mockk",
]
core-ios-test = []

core-common-test-ksp = []
core-android-test-ksp = []
core-ios-test-ksp = []

# Deps for Data Preferences
data-preferences-common = [
    "kotlinx-serialization-json",
    "ksafe",
]
data-preferences-android = []
data-preferences-ios = []

data-preferences-common-ksp = []
data-preferences-android-ksp = []
data-preferences-ios-ksp = []

data-preferences-common-test = []
data-preferences-android-test = []
data-preferences-ios-test = []

data-preferences-common-test-ksp = []
data-preferences-android-test-ksp = []
data-preferences-ios-test-ksp = []

# Deps for Data Remote
data-remote-common = [
    "apollo",
    "apollo-cache",
]
data-remote-android = [
    "apollo-cache-sqlite",
    "ktor-android",
]
data-remote-ios = [
    "apollo-cache-sqlite",
    "ktor-ios",
]

data-remote-common-ksp = []
data-remote-android-ksp = []
data-remote-ios-ksp = []

data-remote-common-test = [
    "apollo-mockserver",
    "apollo-test",
]
data-remote-android-test = []
data-remote-ios-test = []

data-remote-common-test-ksp = []
data-remote-android-test-ksp = []
data-remote-ios-test-ksp = []

# Deps for UI
ui-common = [
    "coil",
    "compose-animation",
    "compose-foundation",
    "compose-material3",
    "compose-material3-adaptive",
    "compose-preview",
    "compose-resources",
    "compose-runtime",
    "compose-runtime-saveable",
    "compose-stability-analyzer-runtime",
    "compose-ui",
    "lifecycle-runtime",
    "lifecycle-viewmodel",
    "kotlinx-serialization-json",
    "metrox-viewmodel",
    "navigation",
    "navigation-material",
    "navigation3-ui",
]
ui-android = [
    "metrox-android",
]
ui-ios = []

ui-common-ksp = []
ui-android-ksp = []
ui-ios-ksp = []

ui-common-test = []
ui-android-test = []
ui-ios-test = []

ui-common-test-ksp = []
ui-android-test-ksp = []
ui-ios-test-ksp = []

app-android = [
    "androidx-activity",
    "androidx-splashscreen",
    "coil",
    "metrox-android",
    "metrox-viewmodel",
]

build-config = [
    "kaml",
    "kotlinpoet",
]

gradle = [
    "gradle-android",
    "gradle-apollo",
    "gradle-baselineprofile",
    "gradle-compose",
    "gradle-compose-compiler",
    "gradle-compose-stability-analyzer",
    "gradle-detekt",
    "gradle-kotest",
    "gradle-kotlin",
    "gradle-kover",
    "gradle-ksp",
    "gradle-metro",
    "gradle-mokkery",
    "gradle-spotless",
]

macrobenchmark = [
    "androidx-benchmark-macro-junit4",
    "androidx-test-ext-junit",
]
