[versions]
apollo = "3.0.0"
compose = "1.1.0-rc01"
compose-compiler = "1.1.0-rc02"
coroutines = "1.6.0"
kotlin = "1.6.10"

# Plugins
detekt = "1.19.0"

# Tests
androidx-test = "1.4.0"
kotest = "5.1.0"
mockk = "1.12.2"

[plugins]
apollo = { id = "com.apollographql.apollo3", version.ref = "apollo" }

[libraries]
# AndroidX
androidx-activity = { module = "androidx.activity:activity-compose", version = "1.4.0" }

# Apollo
apollo = { module = "com.apollographql.apollo3:apollo-runtime", version.ref = "apollo" }

# Compose
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }

# Coroutines
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

# Design
design-material = { module = "com.google.android.material:material", version = "1.5.0" }

# Detekt
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

# Gradle
gradle-android = { module = "com.android.tools.build:gradle", version = "7.0.4" }
gradle-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-updates = { module = "com.github.ben-manes:gradle-versions-plugin", version = "0.41.0" }

# Kotlin
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

# Tests
## AndroidX Test
androidx-test = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
androidx-test-junit = { module = "androidx.test.ext:junit-ktx", version = "1.1.3" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }

## Fixtures
fixtures = { module = "com.appmattus.fixture:fixture", version = "1.2.0" }

## Kotest
kotest = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }

## MockK
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }

## Turbine
turbine = { module = "app.cash.turbine:turbine", version = "0.7.0" }

[bundles]
common = [
    "coroutines",
    "kotlin",
]
common-android = [
    "coroutines-android",
    "kotlin",
]

app = [
    "androidx-activity",
    "design-material",
]

data-remote = [
    "apollo",
]

ui-compose = [
    "compose-animation",
    "compose-foundation",
    "compose-foundation-layout",
    "compose-material",
    "compose-material-icons",
    "compose-ui",
    "compose-ui-tooling",
]

test = [
    "coroutines-test",
    "fixtures",
    "kotest",
    "kotest-assertions-core",
    "mockk",
    "turbine",
]
test-common-android = [
    "coroutines-test",
    "androidx-test",
    "androidx-test-junit",
    "androidx-test-rules",
    "androidx-test-runner",
    "kotest-assertions-core",
    "mockk-android",
    "turbine",
]
test-ui = [
    "compose-ui-test",
]
