extend schema @link(
    url: "https://specs.apollo.dev/cache/v0.4",
    import: ["@fieldPolicy", "@typePolicy"]
)

extend schema @link(
    url: "https://specs.apollo.dev/nullability/v0.4",
    import: ["@semanticNonNull", "@semanticNonNullField", "@catch", "CatchTo", "@catchByDefault"]
)

extend schema @catchByDefault(to: THROW)

# Field Policies
extend type Query @fieldPolicy(forField: "Activity", keyArgs: "id userId mediaId")
extend type Query @fieldPolicy(forField: "ActivityReply", keyArgs: "id")
extend type Query @fieldPolicy(forField: "AiringSchedule", keyArgs: "id mediaId")
extend type Query @fieldPolicy(forField: "Character", keyArgs: "id")
extend type Query @fieldPolicy(forField: "ExternalLinkSourceCollection", keyArgs: "id")
extend type Query @fieldPolicy(forField: "Media", keyArgs: "id")
extend type Query @fieldPolicy(forField: "MediaList", keyArgs: "id mediaId userId")
extend type Query @fieldPolicy(forField: "MediaTrend", keyArgs: "mediaId date")
extend type Query @fieldPolicy(forField: "Recommendation", keyArgs: "id mediaId")
extend type Query @fieldPolicy(forField: "Review", keyArgs: "id mediaId userId")
extend type Query @fieldPolicy(forField: "Staff", keyArgs: "id")
extend type Query @fieldPolicy(forField: "Studio", keyArgs: "id")
extend type Query @fieldPolicy(forField: "Thread", keyArgs: "id userId")
extend type Query @fieldPolicy(forField: "ThreadComment", keyArgs: "id userId")
extend type Query @fieldPolicy(forField: "User", keyArgs: "id")

# Type Policies
extend type ActivityLikeNotification @typePolicy(keyFields: "id userId")
extend type ActivityMentionNotification @typePolicy(keyFields: "id userId")
extend type ActivityMessageNotification @typePolicy(keyFields: "id userId")
extend type ActivityReply @typePolicy(keyFields: "id")
extend type ActivityReplyLikeNotification @typePolicy(keyFields: "id userId")
extend type ActivityReplyNotification @typePolicy(keyFields: "id userId")
extend type ActivityReplySubscribedNotification @typePolicy(keyFields: "id userId")
extend type AiringNotification @typePolicy(keyFields: "id")
extend type AiringSchedule @typePolicy(keyFields: "id mediaId")
extend type Character @typePolicy(keyFields: "id")
extend type CharacterSubmission @typePolicy(keyFields: "id")
extend type CharacterSubmissionUpdateNotification @typePolicy(keyFields: "id")
extend type FollowingNotification @typePolicy(keyFields: "id userId")
extend type ListActivity @typePolicy(keyFields: "id")
extend type Media @typePolicy(keyFields: "id")
extend type MediaDataChangeNotification @typePolicy(keyFields: "id mediaId")
extend type MediaDeletionNotification @typePolicy(keyFields: "id")
extend type MediaExternalLink @typePolicy(keyFields: "id")
extend type MediaList @typePolicy(keyFields: "id mediaId userId")
extend type MediaMergeNotification @typePolicy(keyFields: "id mediaId")
extend type MediaRank @typePolicy(keyFields: "id")
extend type MediaSubmission @typePolicy(keyFields: "id")
extend type MediaSubmissionUpdateNotification @typePolicy(keyFields: "id")
extend type MediaTag @typePolicy(keyFields: "id")
extend type MediaTrend @typePolicy(keyFields: "mediaId date")
extend type MessageActivity @typePolicy(keyFields: "id")
extend type ModAction @typePolicy(keyFields: "id")
extend type Recommendation @typePolicy(keyFields: "id")
extend type RelatedMediaAdditionNotification @typePolicy(keyFields: "id mediaId")
extend type Report @typePolicy(keyFields: "id")
extend type Review @typePolicy(keyFields: "id mediaId userId")
extend type RevisionHistory @typePolicy(keyFields: "id")
extend type Staff @typePolicy(keyFields: "id")
extend type StaffSubmission @typePolicy(keyFields: "id")
extend type StaffSubmissionUpdateNotification @typePolicy(keyFields: "id")
extend type Studio @typePolicy(keyFields: "id")
extend type TextActivity @typePolicy(keyFields: "id")
extend type Thread @typePolicy(keyFields: "id")
extend type ThreadCategory @typePolicy(keyFields: "id")
extend type ThreadComment @typePolicy(keyFields: "id")
extend type ThreadCommentLikeNotification @typePolicy(keyFields: "id userId")
extend type ThreadCommentMentionNotification @typePolicy(keyFields: "id userId")
extend type ThreadCommentReplyNotification @typePolicy(keyFields: "id userId")
extend type ThreadCommentSubscribedNotification @typePolicy(keyFields: "id userId")
extend type ThreadLikeNotification @typePolicy(keyFields: "id userId")
extend type User @typePolicy(keyFields: "id")

# Semantic Non-null Fields
extend type Query @semanticNonNullField(name: "Viewer")
extend type Query @semanticNonNullField(name: "MediaListCollection")
extend type Mutation @semanticNonNullField(name: "UpdateMediaListEntries", levels: [0, 1])
extend type User @semanticNonNullField(name: "avatar")
extend type User @semanticNonNullField(name: "mediaListOptions")
extend type UserAvatar @semanticNonNullField(name: "large")
extend type Media @semanticNonNullField(name: "title")
extend type Media @semanticNonNullField(name: "coverImage")
extend type MediaTitle @semanticNonNullField(name: "userPreferred")
extend type MediaCoverImage @semanticNonNullField(name: "large")
extend type MediaList @semanticNonNullField(name: "score")
extend type MediaList @semanticNonNullField(name: "media")
extend type MediaListCollection @semanticNonNullField(name: "lists", levels: [0, 1])
extend type MediaListCollection @semanticNonNullField(name: "user")
extend type MediaListGroup @semanticNonNullField(name: "name")
extend type MediaListGroup @semanticNonNullField(name: "entries", levels: [0, 1])
extend type MediaListOptions @semanticNonNullField(name: "animeList")
extend type MediaListOptions @semanticNonNullField(name: "mangaList")
extend type MediaListTypeOptions @semanticNonNullField(name: "sectionOrder", levels: [0, 1])
