name: Build Katana

on: [ push ]

env:
  TZ: Europe/Madrid

jobs:
  build:
    runs-on: ubuntu-latest
    container: alvrme/alpine-android:android-31-jdk11
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Cache
        uses: actions/cache@v3
        continue-on-error: true
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties', '**/gradle/libs.versions.toml') }}
      - name: Build Katana
        run: ./gradlew buildDebug detektAll unitTests koverMergedReport
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/reports/kover/report.xml
          flags: unittests
          verbose: true
