name: Clear Cache

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  clearer:
    name: Delete all caches
    runs-on: ubuntu-latest
    steps:
      - name: Clear cache
        uses: easimon/wipe-cache@5f305e3ee1b681c44328cdf11eaedf943b60edff # pin@main
