name: Clear Cache

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  clearer:
    name: Delete all caches
    runs-on: ubuntu-latest
    steps:
      - name: Clear cache
        uses: easimon/wipe-cache@e7ab82e64c328fd39c2e96933d426cd72ac2beba # v2
