name: Deployment

on:
  push:
    branches:
      - develop
    tags:
      - v*

env:
  TZ: Europe/Madrid

jobs:
  cancel-stale-jobs:
    name: Cancel stale jobs
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Stale Jobs
        uses: styfle/cancel-workflow-action@0.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-staging:
    name: Staging deployment
    runs-on: ubuntu-latest
    needs: [ assemble, static-analysis, unit-tests, instrumentation-tests ]
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Common Steps
        uses: ./.github/actions/common-steps
      - name: Decode keystore
        uses: timheuer/base64-to-file@v1.1
        with:
          fileDir: .
          fileName: ${{ secrets.SIGNING_FILE }}
          encodedString: ${{ secrets.SIGNING_FILE_BASE64 }}
      - name: Build staging APK
        env:
          SIGNING_ALIAS: ${{ secrets.SIGNING_ALIAS }}
          SIGNING_ALIAS_PASS: ${{ secrets.SIGNING_ALIAS_PASS }}
          SIGNING_FILE: ${{ secrets.SIGNING_FILE }}
          SIGNING_FILE_PASS: ${{ secrets.SIGNING_FILE_PASS }}
        run: ./gradlew assembleRelease
      - name: Publish staging APK to AppCenter
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: KatanaApp/Katana
          token: ${{ secrets.APPCENTER_TOKEN }}
          group: Testers
          file: app/build/outputs/apk/release/app-release.apk
          notifyTesters: true
          debug: false

  deploy-production:
    name: Production deployment
    runs-on: ubuntu-latest
    needs: [ assemble, static-analysis, unit-tests, instrumentation-tests ]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Common Steps
        uses: ./.github/actions/common-steps
      - name: Decode keystore
        uses: timheuer/base64-to-file@v1.1
        with:
          fileDir: .
          fileName: ${{ secrets.SIGNING_FILE }}
          encodedString: ${{ secrets.SIGNING_FILE_BASE64 }}
      - name: Build production AAB
        env:
          SIGNING_ALIAS: ${{ secrets.SIGNING_ALIAS }}
          SIGNING_ALIAS_PASS: ${{ secrets.SIGNING_ALIAS_PASS }}
          SIGNING_FILE: ${{ secrets.SIGNING_FILE }}
          SIGNING_FILE_PASS: ${{ secrets.SIGNING_FILE_PASS }}
        run: ./gradlew bundleRelease
      - name: Publish production AAB to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
          packageName: dev.alvr.katana
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: completed
          mappingFile: app/build/outputs/mapping/release/mapping.txt
