name: GitHub Actions Version Updater

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.7.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
